[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "49.234.114.189"
port = "5460"
username = "demo"
password = "XXXX"
database = "demo"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"